###
# Gitlab CI
#
# @author Mike Street
# @date 04-2025
#
###

include:
  - project: 'devops/gitlab-ci'
    file:
      - '.gitlab-ci-template.yml'
      - 'v2/jobs/install/npm.yml'
      - 'v2/jobs/lint/eslint.yml'

stages:
  - install
  - lint
  - release

install:npm:
  extends: .install:npm

# Define stages for jobs
lint:eslint:
  extends: .lint:eslint

release:tag:
  stage: release
  extends:
    - .npm:tag:release
