###
# Gitlab CI
#
# @author Mike Street
# @date 06-2021
#
###

include:
  - project: 'devops/gitlab-ci'
    file: '.gitlab-ci-template.yml'

stages:
  - lint
  - release

# Define stages for jobs
js:lint:
  stage: lint
  extends:
    - .js:eslint

release:tag:
  stage: release
  extends:
    - .npm:tag:release
